name: alpine
channels:
  - conda-forge
  - defaults
dependencies:
  - gmsh=4.11.1
  - jax
  - jaxopt
  - numpy=1.24.2
  - pygmo=2.19.5
  - python
  - python-gmsh
  - petsc4py
  - jupyterlab
  - trame
  - ipywidgets
  - scipy=1.10.0
  - scikit-learn
  - pyvista
  - typeguard
  - yaml=0.2.5
  - pygraphviz
  - pip
  - pip:
    - git+https://github.com/alucantonio/dctkit
    - git+https://github.com/alucantonio/deap
    - ray
    - pygmsh
